### ISSUE TITLE
Add bam paths interface not working for local files

### ISSUE THREAD

**Issue by SanderEST** [macarthur-lab/seqr#1104]
I have a local install of seqr, and did the last git pull yesterday. Everything else is working fine, but when I try to add bam paths I get this error:

`Error updating 103484-002-004: (400)`

The gunicorn logs do not reveal much more information:

```
 - - [04/Dec/2019:01:10:04 +0000] "POST /api/project/R0004_proov/upload_alignment_dataset HTTP/1.0" 200 3484 "https://seqr.kliinikum.ee/project/R0004_proov/project_page" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
 - - [04/Dec/2019:01:10:05 +0000] "POST /api/individual/I0000054_103484_002_002/update_alignment_sample HTTP/1.0" 400 2 "https://seqr.kliinikum.ee/project/R0004_proov/project_page" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"

```

In the settings.py file I changed the relevant fields as follows: 

```
# Readviz
READ_VIZ_BAM_PATH = ''
READ_VIZ_CRAM_PATH = ''
```

The exact same file I am trying to upload with bam paths worked in the old schema with set_bam_paths command, but now it is fully depracated.

Any ideas if I could try anything else? Or is it a bug? I saw an open issue similar to this one, but with different error message, and posted long time ago, so decided to open a new issue.

**Comment by hanars** [comment]
Thanks for letting me know. This is still essentially the same issue as https://github.com/macarthur-lab/seqr/issues/720 even though some of the details are different, so I'm going to close out this ticket in favor of that one. I know that one has been open for a while, so I will bump up its priority on my end

**Comment by hanars** [comment]
Sorry for the delay on this, but this should be fixed in the latest version of seqr

**Comment by SanderEST** [comment]
Hi, 

Thank you so much for dealing with this. However, I am sorry, but the issue still seems not to be fixed. I updated my seqr to the latest version (it shows seqr v1.0-a0bae4a1 in bottom left corner), but if I try to upload bam paths, I still get the same message in the dialogue window:` Error updating 103484-002-004: (400).  `

And the gunicorn logs are also the same:

`[18/Jan/2020:02:32:53 +0000] "POST /api/individual/I0000078_103484_002_001/update_alignment_sample HTTP/1.0" 400 2 "https://seqr.kliinikum.ee/project/R0005_genomescan/project_page" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"`

everything else seems to be working, I even created a new project after upgrading seqr, and tried to add bam paths there, but unfortunately it still did not work.

**Comment by hanars** [comment]
Can you confirm that the file path you are putting in for the bam is a valid, full path to the file? Also, can you see in the network tab of developer tools if there is any body to the error response with more information?

**Comment by SanderEST** [comment]
Thank you for dealing this! This time I feel very stupid, there was a typo in a full path. Good thing is that problem is now solved, and I can confirm that readviz works on local install as well. Thank you again!

**Comment by hanars** [comment]
Glad its working for you now!
