### ISSUE TITLE
Issue viewing reads

### ISSUE THREAD

**Issue by lecb** [macarthur-lab/seqr#645]
Having issues with reads not being displayed on case HK104. Error message is:

Error: BAM header contains an invalid BAM magic.

**Comment by hanars** [comment]
Can you please provide a bit more context for this issue. That family exists in 2 projects so I'm not sure which one you are referring to. A link to a search/ saved variants page where this problem is occurring would be helpful

**Comment by lecb** [comment]
Hey Hana,

Sorry, should have been more explicit. It’s in the Estonian WGS cohort - I wasn’t sure how much we are allowed to put on GitHub as it may reveal to much about families/cohorts…

This is the particular variant that is not possible to view reads for: https://seqr.broadinstitute.org/project/R0332_cmg_estonia_wgs/saved_variants/variant/SV0032725_x124963583_r0332_cmg

Hope this helps,
BW
Ellie

On Nov 9, 2018, at 10:38 AM, hanars <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you please provide a bit more context for this issue. That family exists in 2 projects so I'm not sure which one you are referring to. A link to a search/ saved variants page where this problem is occurring would be helpful

**Comment by hanars** [comment]
thanks! In the future if there is an issue you want to submit and are worried about posting info publicly, you can submit the issues at https://github.com/macarthur-lab/seqr-private

**Comment by lecb** [comment]
Ahhh didn’t know that! Thanks!
E

On Nov 9, 2018, at 2:31 PM, hanars <notifications@github.com<mailto:notifications@github.com>> wrote:


thanks! In the future if there is an issue you want to submit and are worried about posting info publicly, you can submit the issues at https://github.com/macarthur-lab/seqr-private<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmacarthur-lab%2Fseqr-private&data=01%7C01%7CE.Seaby%40soton.ac.uk%7C47224840fdae4bf4dd5408d64679f7db%7C4a5378f929f44d3ebe89669d03ada9d8%7C1&sdata=nPun22jhJnRYrO%2FclniQm8VL%2FtEAa0fT6WreS%2BDxN%2B0%3D&reserved=0>

**Comment by hanars** [comment]
per https://github.com/macarthur-lab/seqr/issues/652 this is an issue with all families in this cohort, as well as Estonian external exomes and CMG_Estonia_WES

**Comment by hanars** [comment]
WES issues are fixed, crams for WGS are moved

**Comment by hanars** [comment]
Having looked into this more, this should not be affecting all families. There is one family whose bams appear to be missing, **HK017**.  @ Jchangster will look into it, although probably not until after thanksgiving

Families with crams are also currently not working due to the crams being moved. We are in the process of fixing this. This affects the following families:
HK053
HK069
HK072
HK073
HK075
HK087
HK090
HK095
HK101
HK102
HK103
HK104
HK106

**Comment by kounap** [comment]
Hi Hana,
I have a question about this list of cases which reads are not seen (list above). I still cannot open reads for these cases. can you tell me when I can expect to fix this problem?
Kati

**Comment by hanars** [comment]
Reads have been fixed for all the affected families except for HK104 which is being separately tracked in https://github.com/macarthur-lab/seqr/issues/774
