### ISSUE TITLE
"No sample fields found for index" error when adding elastic search index to a project

### ISSUE THREAD

**Issue by nvteja** [macarthur-lab/seqr#781]
Hello,

I have seqr local installation on ubuntu 16.04. After loading the data into elastic search using `load_dataset_to_es.py` script, I tried to link the elastic search index to the seqr project, but seqr keeps throwing "No sample fields found for index <index name>" error. 

Here are the commands I used to load the data into seqr. The project was created and sample information was loaded in seqr prior to running these commands..

```
GENOME_VERSION="37"      
SAMPLE_TYPE="WES"         
DATASET_TYPE="VARIANTS"    
PROJECT_GUID="R0005_c2_181_final_teja"  
INPUT_VCF="/home/arun/seqr_data/C2-181_CA0249.orig.vcf"

python2.7 gcloud_dataproc/submit.py --run-locally hail_scripts/v01/load_dataset_to_es.py  --spark-home $SPARK_HOME --genome-version $GENOME_VERSION --project-guid $PROJECT_GUID --sample-type $SAMPLE_TYPE --dataset-type $DATASET_TYPE --skip-validation  --exclude-hgmd --vep-block-size 100 --es-block-size 10 --num-shards 1 --hail-version 0.1 --use-nested-objects-for-vep --use-nested-objects-for-genotypes $INPUT_VCF
```

Elastic search logs seem to indicate the export  finished without any errors.. Pasting last few lines of the log here.
```
2019-03-12 21:57:08,472 INFO     PUT http://localhost:9200/index_operations_log/_mapping/log [status:200 request:0.009s]
2019-03-12 21:57:08,519 INFO     POST http://localhost:9200/index_operations_log/log?op_type=index [status:201 request:0.043s]
2019-03-12 21:57:08,519 INFO     Saved index operation metadata:
2019-03-12 21:57:08,520 INFO     {'command': '/home/arun/seqr/seqr/hail_elasticsearch_pipelines/hail_scripts/v01/load_dataset_to_es.py --genome-version 37 --project-guid R0005_c2_181_final_teja --sample-type WES --dataset-type VARIANTS --skip-validation --exclude-hgmd --vep-block-size 100 --es-block-size 10 --num-shards 1 --use-nested-objects-for-vep --use-nested-objects-for-genotypes /home/arun/seqr_data/C2-181_CA0249.orig.vcf --username arun --directory seqr-dev:/home/arun/seqr/seqr/hail_elasticsearch_pipelines',
 'dataset_type': 'VARIANTS',
 'directory': 'seqr-dev:/home/arun/seqr/seqr/hail_elasticsearch_pipelines',
 'fam_file': None,
 'genome_version': '37',
 'index_name': 'r0005_c2_181_final_teja__wes__grch37__variants__20190312',
 'operation': 'create_index',
 'project_id': 'R0005_c2_181_final_teja',
 'remap_sample_ids': None,
 'sample_type': 'WES',
 'skip_vep': False,
 'source_file': '/home/arun/seqr_data/C2-181_CA0249.orig.vcf',
 'status': 'success',
 'subset_samples': None,
 'timestamp': '20190312-215708',
 'username': 'arun'}
2019-03-12 21:57:08,520 INFO     ==> delete intermediate vds files
2019-03-12 21:57:08,520 INFO     ==> Pipeline completed
2019-03-12 21:57:08,520 INFO     
2019-03-12 21:57:08,520 INFO     
2019-03-12 21:57:08,520 INFO     
2019-03-12 21:57:08,520 INFO     ========================================================================================================
2019-03-12 21:57:08,520 INFO     
2019-03-12 21:57:08,520 INFO     ==> To add this dataset to a seqr project, click 'Edit Datasets' on the seqr project page 
2019-03-12 21:57:08,520 INFO         (https://seqr.broadinstitute.org/project/R0005_c2_181_final_teja/project_page)  and enter: 
2019-03-12 21:57:08,520 INFO     
2019-03-12 21:57:08,520 INFO             Elasticsearch Index: r0005_c2_181_final_teja__wes__grch37__variants__20190312 
2019-03-12 21:57:08,520 INFO             Sample Type: WES 
2019-03-12 21:57:08,520 INFO             Dataset Path: /home/arun/seqr_data/C2-181_CA0249.orig.vcf 
2019-03-12 21:57:08,520 INFO     
2019-03-12 21:57:08,520 INFO     ========================================================================================================
2019-03-12 21:57:08,520 INFO     
2019-03-12 21:57:08,520 INFO     
/home/arun/seqr/seqr/../bin/spark-2.0.2-bin-hadoop2.7/bin/spark-submit                  --driver-memory 5G         --executor-memory 5G         --num-executors 2         --conf spark.driver.extraJavaOptions=-Xss4M         --conf spark.executor.extraJavaOptions=-Xss4M         --conf spark.executor.memoryOverhead=5g         --conf spark.driver.maxResultSize=30g         --conf spark.kryoserializer.buffer.max=1g         --conf spark.memory.fraction=0.1         --conf spark.default.parallelism=1         --jars hail_builds/v01/hail-v01-10-8-2018-90c855449.jar         --conf spark.driver.extraClassPath=hail_builds/v01/hail-v01-10-8-2018-90c855449.jar         --conf spark.executor.extraClassPath=hail_builds/v01/hail-v01-10-8-2018-90c855449.jar         --py-files hail_builds/v01/hail-v01-10-8-2018-90c855449.zip         "hail_scripts/v01/load_dataset_to_es.py" "--genome-version" "37" "--project-guid" "R0005_c2_181_final_teja" "--sample-type" "WES" "--dataset-type" "VARIANTS" "--skip-validation" "--exclude-hgmd" "--vep-block-size" "100" "--es-block-size" "10" "--num-shards" "1" "--use-nested-objects-for-vep" "--use-nested-objects-for-genotypes" "/home/arun/seqr_data/C2-181_CA0249.orig.vcf" --username 'arun' --directory 'seqr-dev:/home/arun/seqr/seqr/hail_elasticsearch_pipelines
```

Here is the error I get when I try to link the elastic search index to the 

![Screen Shot 2019-03-13 at 8 58 08 AM](https://user-images.githubusercontent.com/16638984/54280612-45b94680-456e-11e9-8dcb-36d13c85419f.png)

Could you please advise me on how to get past this issue?

Thank you,
Teja.

**Comment by hanars** [comment]
Hi Teja,

Unfortunately, it looks like you ran the loading command on an outdated version of the pipeline which means that the index is not properly configured for seqr. Please pull the latest version of code and try re-running the pipeline using the same command as before

Best,
Hana

**Comment by nvteja** [comment]
Thank you Hana! After I git pulled the latest scripts, I get 404 error not found when i click on a project name.

**Comment by hanars** [comment]
You should not need to do a full reinstall. Running `./manage.py migrate` should fix this issue

**Comment by nvteja** [comment]
Sorry Hana, for some reason even after the git pull and db migration I still get the same error.  I created a new project, loaded sample information and then inserted data into elastic search, just like before and when I try to add the elastic search index to the project, I get the same error "No sample fields found for index" error...

**Comment by hanars** [comment]
Hi Teja,

As I said before, you need to completely re-run the loading pipeline from the beginning and generate a new index, and then try adding that new index

**Comment by nvteja** [comment]
Hi Hana,

I am sorry, but what steps are necessary to completely re-run the loading pipeline? After git-pull and migration, I ran all the commands by following instructions from this page [https://github.com/macarthur-lab/seqr/blob/master/deploy/LOCAL_INSTALL.md]

i.e. 

```cd ${SEQR_DIR}/hail_elasticsearch_pipelines/  
  
GENOME_VERSION="37"        # should be "37" or "38"
SAMPLE_TYPE="WES"          # can be "WES" or "WGS"
DATASET_TYPE="VARIANTS"    # can be "VARIANTS" (for GATK VCFs) or "SV" (for Manta VCFs)
PROJECT_GUID="R001_test"   # should match the ID in the url of the project page 
INPUT_VCF="test.vcf.gz"    # local path of VCF file
 
python2.7 gcloud_dataproc/submit.py --run-locally hail_scripts/v01/load_dataset_to_es.py  --spark-home $SPARK_HOME --genome-version $GENOME_VERSION --project-guid $PROJECT_GUID --sample-type $SAMPLE_TYPE --dataset-type $DATASET_TYPE --skip-validation  --exclude-hgmd --vep-block-size 100 --es-block-size 10 --num-shards 1 --hail-version 0.1 --use-nested-objects-for-vep --use-nested-objects-for-genotypes $INPUT_VCF```

and I used the name of the index from the last command to link the elastic search to seqr project.


Are there additional steps before/after these commands that I need to run? The only other commands in the link above are the installation scripts. I am very sorry if I am missing/not seeing any obvious steps that need to be re-run.

Thank you,
Teja.

**Comment by hanars** [comment]
Can you try running 

```
cd ${SEQR_DIR}/hail_elasticsearch_pipelines/
git pull origin master
```
If it says "Already up to date" can you then run "git log" and send me the output (the top 20is rows is fine). If it pulls new files, try re-running the pipeline again

**Comment by nvteja** [comment]
Aah that did it! I didnt realize that there were 2 independent git repos. I just pulled the updates to the main seqr code and not the hail_elasticsearch_pipelines. It works now! Thank you so much for your patience!

**Comment by hanars** [comment]
so glad that worked!
